export interface Slicer{
  slicerId: number,
  enableRetraction: boolean,
  retractionDIstance: number,
  retractionSpeed: number,
  enablePrintCooling: boolean,
  fanSpeed: number,
  regFanSpeed: number,
  maxFanSpeed: number,
  fanSpeedThreshold: number,
  initFanSpeed: number,
  regFanSpeedAtLayer: number,
  printSpeedRecommended: number,
  initLayerSpeed: number,
  printSpeedMax: number,
  printSpeedMin: number,
  printingTemp: number,
  printingTempInitLayer:number,
  printingTempMin: number,
  printingTempMax:number,
  bedTempMin: number,
  bedTempMax: number,
  bedTempRecommended: number,
  layerHeight: number,
  initLayerHeight: number
}
